import { IGarageFloor, ParkingSpotType } from '../models/garage'

// The inital store
export const initial: IGarageFloor[] = [
	{
		name: 'Floor One',
		capacity: 10,
		available: 8,
		spots: [
			{
				type: ParkingSpotType.COMPACT,
				occupied: true,
				occupationStartedAt: new Date(),
				occupationEndedAt: null,
				duration: 0,
				currentRate: 0,
			},
			{
				type: ParkingSpotType.COMPACT,
				occupied: true,
				occupationStartedAt: new Date(),
				occupationEndedAt: null,
				duration: 0,
				currentRate: 0,
			},
			{
				type: ParkingSpotType.COMPACT,
				occupied: false,
				occupationStartedAt: null,
				occupationEndedAt: null,
				duration: 0,
				currentRate: 0,
			},
			{
				type: ParkingSpotType.LARGE,
				occupied: false,
				occupationStartedAt: null,
				occupationEndedAt: null,
				duration: 0,
				currentRate: 0,
			},
			{
				type: ParkingSpotType.LARGE,
				occupied: false,
				occupationStartedAt: null,
				occupationEndedAt: null,
				duration: 0,
				currentRate: 0,
			},
			{
				type: ParkingSpotType.LARGE,
				occupied: false,
				occupationStartedAt: null,
				occupationEndedAt: null,
				duration: 0,
				currentRate: 0,
			},
			{
				type: ParkingSpotType.HANDICAP,
				occupied: false,
				occupationStartedAt: null,
				occupationEndedAt: null,
				duration: 0,
				currentRate: 0,
			},
			{
				type: ParkingSpotType.HANDICAP,
				occupied: false,
				occupationStartedAt: null,
				occupationEndedAt: null,
				duration: 0,
				currentRate: 0,
			},
			{
				type: ParkingSpotType.MOTORCYCLE,
				occupied: false,
				occupationStartedAt: null,
				occupationEndedAt: null,
				duration: 0,
				currentRate: 0,
			},
			{
				type: ParkingSpotType.MOTORCYCLE,
				occupied: false,
				occupationStartedAt: null,
				occupationEndedAt: null,
				duration: 0,
				currentRate: 0,
			},
		],
	},
	{
		name: 'Floor two',
		capacity: 10,
		available: 5,
		spots: [
			{
				type: ParkingSpotType.COMPACT,
				occupied: true,
				occupationStartedAt: new Date(),
				occupationEndedAt: null,
				duration: 0,
				currentRate: 0,
			},
			{
				type: ParkingSpotType.COMPACT,
				occupied: true,
				occupationStartedAt: new Date(),
				occupationEndedAt: null,
				duration: 0,
				currentRate: 0,
			},
			{
				type: ParkingSpotType.COMPACT,
				occupied: false,
				occupationStartedAt: null,
				occupationEndedAt: null,
				duration: 0,
				currentRate: 0,
			},
			{
				type: ParkingSpotType.LARGE,
				occupied: true,
				occupationStartedAt: new Date(),
				occupationEndedAt: null,
				duration: 0,
				currentRate: 0,
			},
			{
				type: ParkingSpotType.LARGE,
				occupied: false,
				occupationStartedAt: null,
				occupationEndedAt: null,
				duration: 0,
				currentRate: 0,
			},
			{
				type: ParkingSpotType.LARGE,
				occupied: false,
				occupationStartedAt: null,
				occupationEndedAt: null,
				duration: 0,
				currentRate: 0,
			},
			{
				type: ParkingSpotType.HANDICAP,
				occupied: true,
				occupationStartedAt: new Date(),
				occupationEndedAt: null,
				duration: 0,
				currentRate: 0,
			},
			{
				type: ParkingSpotType.HANDICAP,
				occupied: false,
				occupationStartedAt: null,
				occupationEndedAt: null,
				duration: 0,
				currentRate: 0,
			},
			{
				type: ParkingSpotType.MOTORCYCLE,
				occupied: true,
				occupationStartedAt: new Date(),
				occupationEndedAt: null,
				duration: 0,
				currentRate: 0,
			},
			{
				type: ParkingSpotType.MOTORCYCLE,
				occupied: false,
				occupationStartedAt: null,
				occupationEndedAt: null,
				duration: 0,
				currentRate: 0,
			},
		],
	},
]
